create or replace trigger "F15A6_RFE_T1"
AFTER
insert on "F15A6_RFE"
for each row
DECLARE
  lab_id_var NUMBER;
  sys_admin_id NUMBER;
  lab_dir_id NUMBER;
  chair_id NUMBER;
  exec_dir_id NUMBER;
BEGIN
  
  
  DBMS_OUTPUT.PUT_LINE('HERE 1');
  
  SELECT F15A6_LAB_LAB_ID INTO lab_id_var FROM F15A6_EMP
  WHERE emp_id = :new.F15A6_EMP_EMP_ID;
  
  
  DBMS_OUTPUT.PUT_LINE('HERE 2');
  SELECT emp_id INTO sys_admin_id FROM F15A6_Emp
  WHERE F15A6_LAB_LAB_ID = lab_id_var AND emp_status = 'A'
    AND SYS_ADMIN_FLAG = 'Y';
	
	DBMS_OUTPUT.PUT_LINE('HERE 3');
  SELECT emp_id INTO lab_dir_id FROM F15A6_Emp
  WHERE F15A6_LAB_LAB_ID = lab_id_var AND emp_status = 'A'
    AND LAB_DIRECTOR_FLAG = 'Y';
	
	DBMS_OUTPUT.PUT_LINE('HERE 4');
  SELECT emp_id INTO chair_id FROM F15A6_Emp
  WHERE emp_status = 'A' AND CHAIRPERSON_FLAG = 'Y';
  
  DBMS_OUTPUT.PUT_LINE('HERE 5');
  SELECT emp_id INTO exec_dir_id FROM F15A6_Emp
  WHERE emp_status = 'A' AND EXEC_DIRECTOR_FLAG = 'Y';
  
  DBMS_OUTPUT.PUT_LINE('HERE 6');
  INSERT INTO F15A6_RTC (code_id, role_type, description,
    F15A6_RFE_RFE_ID, F15A6_EMP_EMP_ID) VALUES
  (F15A6_RTC_SEQ.NEXTVAL, 'Approver', ' ', :new.RFE_ID, sys_admin_id);
  
  DBMS_OUTPUT.PUT_LINE('HERE 7');
  INSERT INTO F15A6_RTC (code_id, role_type, description,
    F15A6_RFE_RFE_ID, F15A6_EMP_EMP_ID) VALUES
  (F15A6_RTC_SEQ.NEXTVAL, 'Approver', ' ', :new.RFE_ID, lab_dir_id);
  
  DBMS_OUTPUT.PUT_LINE('HERE 8');
  INSERT INTO F15A6_RTC (code_id, role_type, description,
    F15A6_RFE_RFE_ID, F15A6_EMP_EMP_ID) VALUES
  (F15A6_RTC_SEQ.NEXTVAL, 'Approver', ' ', :new.RFE_ID, chair_id);
  
  DBMS_OUTPUT.PUT_LINE('HERE 9');
  INSERT INTO F15A6_RTC (code_id, role_type, description,
    F15A6_RFE_RFE_ID, F15A6_EMP_EMP_ID) VALUES
  (F15A6_RTC_SEQ.NEXTVAL, 'Approver', ' ', :new.RFE_ID, exec_dir_id);
  
  DBMS_OUTPUT.PUT_LINE('HERE 10');
END;

create or replace TRIGGER status_history_trigger 
AFTER INSERT 
ON F15A6_RFE 
FOR EACH ROW 
 
BEGIN 
 INSERT INTO F15A6_STAT_HIS (HISTORY_ID, F15A6_STATUS_STATUS_ID, F15A6_RFE_RFE_ID, F15A6_EMP_EMP_ID) 
                         VALUES(DEFAULT, 100, :NEW.RFE_ID, :NEW.F15A6_EMP_EMP_ID); 
END; 

select "EMP_ID", 
"EMP_NAME",
"EMP_EMAIL",
"EMP_OFFICE",
"EMP_PHONE",
"EMP_STATUS",
"STATUS_EFF_DATE",
"SYS_ADMIN_FLAG",
"LAB_DIRECTOR_FLAG",
"EXEC_DIRECTOR_FLAG",
"CHAIRPERSON_FLAG",
a."ACCESS_LEVEL",
l."LAB_CODE"
from "#OWNER#"."F15A6_EMP" e
join "#OWNER#"."F15A6_AUTH" a
    on e."F15A6_AUTH_AUTH_ID" = a."AUTH_ID"
join "#OWNER#"."F15A6_LAB" l
    on e."F15A6_LAB_LAB_ID" = l."LAB_ID";
	
select "AUTH_ID", 
"ACCESS_LEVEL"
from "#OWNER#"."F15A6_AUTH";
  
select "LAB_ID", 
"LAB_NAME",
"LAB_CODE",
"DESCRIPTION"
from "#OWNER#"."F15A6_LAB";
  
select "RFE_ID",
e."EMP_NAME" AS "Requester",
"EXPLANATION",
"ALT_PROJECTIONS",
"APPROVAL_REVIEW_DATE",
s."STATUS"
from "#OWNER#"."F15A6_RFE" r
   join "#OWNER#"."F15A6_STATUS" s
   on r.F15A6_STATUS_STATUS_ID =    s.status_id
   join "#OWNER#"."F15A6_EMP" e
   on r."F15A6_EMP_EMP_ID" = e."EMP_ID"
   left join "#OWNER#"."F15A6_RTC" rtc
   on (r."RFE_ID" = rtc."F15A6_RFE_RFE_ID") AND
       (rtc."F15A6_EMP_EMP_ID" = :CUR_USER)
where r."F15A6_EMP_EMP_ID" = :CUR_USER OR
   rtc."F15A6_EMP_EMP_ID" = :CUR_USER;

select F15A6_STATUS_STATUS_ID,
       F15A6_EMP_EMP_ID,
       CREATED
  from F15A6_STAT_HIS WHERE F15A6_RFE_RFE_ID = :P9_RFE_ID ORDER BY CREATED DESC;
  
  select r."CODE_ID",
r."ROLE_TYPE",
r."DESCRIPTION",
e.emp_name AS "Employee"
from "#OWNER#"."F15A6_RTC" r
join "#OWNER#"."F15A6_EMP" e
  on r."F15A6_EMP_EMP_ID" = e.emp_id
where r."F15A6_RFE_RFE_ID" = :P9_RFE_ID;

select "DOCUMENT_ID", 
"FILENAME",
"MIMETYPE",
"DESCRIPTION",
dbms_lob.getlength("DOCUMENT") "DOCUMENT"
from "#OWNER#"."F15A6_DOCUMENT"
where "F15A6_RFE_RFE_ID" = :P9_RFE_ID;

select "TASK_ID", 
"EFFECTIVE_DATE",
"TASK_ABBREVIATION",
"TASK_DESCRIPTION"
from "#OWNER#"."F15A6_TASK"
where "TASK_ID" IN (SELECT F15A6_TASK_TASK_ID FROM F15A6_TASK_JUN WHERE F15A6_RFE_RFE_ID = :P9_RFE_ID);

select c."COMMENT_ID", 
c."COMMENT_VAL" "Comment",
c."ENTRY_DATE",
e."EMP_NAME" "Employee"
from "#OWNER#"."F15A6_COMMENT" c
join "#OWNER#"."F15A6_EMP" e
  on c."F15A6_EMP_EMP_ID" = e."EMP_ID"
where c."F15A6_RFE_RFE_ID" = :P9_RFE_ID;

SELECT emp_id || ': ' || emp_name FROM F15A6_Emp
WHERE SYS_ADMIN_FLAG = 'Y'
    AND F15A6_LAB_LAB_ID = :CUR_LAB
    AND emp_status = 'A';
	
SELECT emp_id || ': ' || emp_name FROM F15A6_Emp
WHERE LAB_DIRECTOR_FLAG = 'Y'
    AND F15A6_LAB_LAB_ID = :CUR_LAB
    AND emp_status = 'A';
	
SELECT emp_id || ': ' || emp_name FROM F15A6_Emp
WHERE CHAIRPERSON_FLAG = 'Y'
    AND emp_status = 'A';
	
SELECT emp_id || ': ' || emp_name FROM F15A6_Emp
WHERE EXEC_DIRECTOR_FLAG = 'Y'
    AND emp_status = 'A';

	SELECT e.* FROM F15A6_EMP e
JOIN F15A6_RTC r
    ON e.emp_id = r.F15A6_EMP_EMP_ID
JOIN F15A6_RFE rfe
    ON r.F15A6_RFE_RFE_ID = rfe.RFE_ID
WHERE r.F15A6_RFE_RFE_ID = :P9_RFE_ID
    AND r.ROLE_TYPE = 'Approver'
    AND e.EMP_STATUS = 'A'
    AND e.EMP_ID = :CUR_USER
    AND rfe.F15A6_STATUS_STATUS_ID NOT IN (100, 121, 122, 123, 127);
	
	:P9_F15A6_STATUS_STATUS_ID NOT IN (100, 121, 122, 123, 127) AND :P9_CUR_USER_ID = :CUR_USER;
	
	:P9_F15A6_STATUS_STATUS_ID IN (100, 121, 122) AND :P9_RFE_ID IS NOT NULL AND :P9_CUR_USER_ID = :CUR_USER;
	
	SELECT e.* FROM F15A6_EMP e
JOIN F15A6_RTC r
    ON e.emp_id = r.F15A6_EMP_EMP_ID
JOIN F15A6_RFE rfe
    ON r.F15A6_RFE_RFE_ID = rfe.RFE_ID
WHERE r.F15A6_RFE_RFE_ID = :P9_RFE_ID
    AND r.ROLE_TYPE = 'Approver'
    AND e.EMP_STATUS = 'A'
    AND e.EMP_ID = :CUR_USER
    AND rfe.F15A6_STATUS_STATUS_ID NOT IN (100, 121, 122, 123, 127);
	
	
	SELECT e.* FROM F15A6_EMP e
JOIN F15A6_RTC r
    ON e.emp_id = r.F15A6_EMP_EMP_ID
JOIN F15A6_RFE rfe
    ON r.F15A6_RFE_RFE_ID = rfe.RFE_ID
WHERE r.F15A6_RFE_RFE_ID = :P9_RFE_ID
    AND r.ROLE_TYPE = 'Approver'
    AND e.SYS_ADMIN_FLAG = 'Y'
    AND e.EMP_STATUS = 'A'
    AND rfe.F15A6_STATUS_STATUS_ID = 120
    AND e.EMP_ID = :CUR_USER;
	
	SELECT e.* FROM F15A6_EMP e
JOIN F15A6_RTC r
    ON e.emp_id = r.F15A6_EMP_EMP_ID
JOIN F15A6_RFE rfe
    ON r.F15A6_RFE_RFE_ID = rfe.RFE_ID
WHERE r.F15A6_RFE_RFE_ID = :P9_RFE_ID
    AND r.ROLE_TYPE = 'Approver'
    AND e.LAB_DIRECTOR_FLAG = 'Y'
    AND e.EMP_STATUS = 'A'
    AND rfe.F15A6_STATUS_STATUS_ID = 124
    AND e.EMP_ID = :CUR_USER;
	
	SELECT e.* FROM F15A6_EMP e
JOIN F15A6_RTC r
    ON e.emp_id = r.F15A6_EMP_EMP_ID
JOIN F15A6_RFE rfe
    ON r.F15A6_RFE_RFE_ID = rfe.RFE_ID
WHERE r.F15A6_RFE_RFE_ID = :P9_RFE_ID
    AND r.ROLE_TYPE = 'Approver'
    AND e.CHAIRPERSON_FLAG = 'Y'
    AND e.EMP_STATUS = 'A'
    AND rfe.F15A6_STATUS_STATUS_ID = 125
    AND e.EMP_ID = :CUR_USER;
	
	SELECT e.* FROM F15A6_EMP e
JOIN F15A6_RTC r
    ON e.emp_id = r.F15A6_EMP_EMP_ID
JOIN F15A6_RFE rfe
    ON r.F15A6_RFE_RFE_ID = rfe.RFE_ID
WHERE r.F15A6_RFE_RFE_ID = :P9_RFE_ID
    AND r.ROLE_TYPE = 'Approver'
    AND e.EXEC_DIRECTOR_FLAG = 'Y'
    AND e.EMP_STATUS = 'A'
    AND rfe.F15A6_STATUS_STATUS_ID = 126
    AND e.EMP_ID = :CUR_USER;
	
	select "STATUS_ID", 
"STATUS",
"DESCRIPTION"
from "#OWNER#"."F15A6_STATUS";

select "EMP_ID", 
"EMP_NAME",
"EMP_EMAIL",
"EMP_OFFICE",
"EMP_PHONE",
"EMP_STATUS",
"STATUS_EFF_DATE",
"SYS_ADMIN_FLAG",
"LAB_DIRECTOR_FLAG",
"EXEC_DIRECTOR_FLAG",
"CHAIRPERSON_FLAG",
"F15A6_AUTH_AUTH_ID",
"F15A6_LAB_LAB_ID"
from "#OWNER#"."F15A6_SYS_ADMIN_VIEW";
  
  
  select "EMP_ID", 
"EMP_NAME",
"EMP_EMAIL",
"EMP_OFFICE",
"EMP_PHONE",
"EMP_STATUS",
"STATUS_EFF_DATE",
"SYS_ADMIN_FLAG",
"LAB_DIRECTOR_FLAG",
"EXEC_DIRECTOR_FLAG",
"CHAIRPERSON_FLAG",
"F15A6_AUTH_AUTH_ID",
"F15A6_LAB_LAB_ID"
from "#OWNER#"."F15A6_REQUESTER_VIEW";
  
  
  select "EMP_ID", 
"EMP_NAME",
"EMP_EMAIL",
"EMP_OFFICE",
"EMP_PHONE",
"EMP_STATUS",
"STATUS_EFF_DATE",
"SYS_ADMIN_FLAG",
"LAB_DIRECTOR_FLAG",
"EXEC_DIRECTOR_FLAG",
"CHAIRPERSON_FLAG",
"F15A6_AUTH_AUTH_ID",
"F15A6_LAB_LAB_ID"
from "#OWNER#"."F15A6_LAB_DIRECTOR_VIEW";


select "EMP_ID", 
"EMP_NAME",
"EMP_EMAIL",
"EMP_OFFICE",
"EMP_PHONE",
"EMP_STATUS",
"STATUS_EFF_DATE",
"SYS_ADMIN_FLAG",
"LAB_DIRECTOR_FLAG",
"EXEC_DIRECTOR_FLAG",
"CHAIRPERSON_FLAG",
"F15A6_AUTH_AUTH_ID",
"F15A6_LAB_LAB_ID"
from "#OWNER#"."F15A6_CHAIRPERSON_VIEW";
  
  
  select "EMP_ID", 
"EMP_NAME",
"EMP_EMAIL",
"EMP_OFFICE",
"EMP_PHONE",
"EMP_STATUS",
"STATUS_EFF_DATE",
"SYS_ADMIN_FLAG",
"LAB_DIRECTOR_FLAG",
"EXEC_DIRECTOR_FLAG",
"CHAIRPERSON_FLAG",
"F15A6_AUTH_AUTH_ID",
"F15A6_LAB_LAB_ID"
from "#OWNER#"."F15A6_EXEC_DIR_VIEW"; 
  
  select RFE_ID,
       EXPLANATION,
       ALT_PROJECTIONS,
       APPROVAL_REVIEW_DATE,
       F15A6_STATUS_STATUS_ID,
       F15A6_EMP_EMP_ID
  from F15A6_RFE;
  
  select RFE_ID,
       EXPLANATION,
       ALT_PROJECTIONS,
       APPROVAL_REVIEW_DATE,
       F15A6_STATUS_STATUS_ID,
       F15A6_EMP_EMP_ID
  from F15A6_RFE WHERE
  APPROVAL_REVIEW_DATE BETWEEN SYSDATE -35 AND SYSDATE;
  
  select RFE_ID,
       EXPLANATION,
       ALT_PROJECTIONS,
       APPROVAL_REVIEW_DATE,
       F15A6_STATUS_STATUS_ID,
       F15A6_EMP_EMP_ID
  from F15A6_RFE WHERE
  APPROVAL_REVIEW_DATE BETWEEN SYSDATE AND SYSDATE + 35;



	